### ISSUE TITLE
/usr/local/bin/cloudflared: No such file or directory on x86_64

### ISSUE THREAD

**Issue by SebastianMuskalla** [testdasi/pihole-with-doh#2]
I'm running this container on a Raspi 4 without any problem, but if I try to run it on an x86_64 system, the container never
 manages to start.

Here is the log:
```
Starting pihole-FTL (no-daemon) as root
Starting stubby
[13:24:22.483301] STUBBY: Read config from file /config/stubby.yml
Starting cloudflared
./run: line 7: /usr/local/bin/cloudflared: No such file or directory
Stopping stubby
Stopping pihole-FTL
Stopping cloudflared
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
cloudflared: no process found
```

Here is the `docker-compose.yml` I am using to start the container:
```
version: "3"

services:
    pihole-dot-doh:
        container_name: pihole-dot-doh
        image: testdasi/pihole-dot-doh:latest
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "10443:443/tcp"
        environment:
            - TZ=Europe/Berlin
            - WEBPASSWORD=<REMOVED>
            - DNS1=127.1.1.1#5153
            - DNS2=127.2.2.2#5253
            - ServerIP=<REMOVED>
            - ServerIPv6=
            - IPv6=False
            - DNSMASQ_LISTENING=all
        volumes:
            - '/docker/volumes/pihole-dot-doh/pihole/:/etc/pihole/'
            - '/docker/volumes/pihole-dot-doh/dnsmasq.d/:/etc/dnsmasq.d/'
            - '/docker/volumes/pihole-dot-doh/log/pihole.log:/var/log/pihole.log'
            - '/docker/volumes/pihole-dot-doh/config/:/config'
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
```
